# Generated by Django 5.1.5 on 2026-06-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationjob',
            name='kind',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], default='image', max_length=12),
        ),
    ]
