# Generated by Django 5.1.5 on 2026-06-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0002_alter_generationjob_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationjob',
            name='kind',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('ugc', 'UGC')], default='image', max_length=12),
        ),
    ]
