# Generated by Django 5.1.5 on 2026-06-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='asset',
            name='higgsfield_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='asset',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
