# Generated by Django 5.1.5 on 2026-06-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_asset_content_hash_asset_higgsfield_url_asset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
