# Generated by Django 5.1.5 on 2026-06-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompton', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
